version: '3'

services:
  consul:
    image: consul:1.15.4
    ports:
      - "8500:8500"

  zanzibar:
    build: .
    ports:
      - "5000:5000"
    environment:
      - CONSUL_HOST=consul
      - CONSUL_PORT=8500
      - FLASK_ENV=production
    volumes:
      - ./server.crt:/app/server.crt
      - ./server.key:/app/server.key
    depends_on:
      - consul
